import * as fs from 'fs';
import * as path from 'path';

const DEFAULT_CONFIG = `
schema: 1
partialsDir: docs/agent-partials
templatesDir: docs/agent-templates
output: 
  - agent: gemini
    template: gemini.md.tmpl
    outFile: GEMINI.md
`;

const DEFAULT_TEMPLATE = `
<!-- Generated by agent-context. Do not edit directly. -->

{{> overview }}
`;

const DEFAULT_PARTIAL = `
# Project Overview

This is the project overview.
`;

export function initCommand() {
  const rootDir = process.cwd();

  const configPath = path.join(rootDir, '.agent-instructions.yaml');
  const partialsDir = path.join(rootDir, 'docs/agent-partials');
  const templatesDir = path.join(rootDir, 'docs/agent-templates');

  // Create config file
  if (!fs.existsSync(configPath)) {
    fs.writeFileSync(configPath, DEFAULT_CONFIG);
    console.error(`Created config file: ${configPath}`);
  } else {
    console.error(`Config file already exists: ${configPath}`);
  }

  // Create partials directory and file
  if (!fs.existsSync(partialsDir)) {
    fs.mkdirSync(partialsDir, { recursive: true });
  }
  const partialPath = path.join(partialsDir, 'overview.md');
  if (!fs.existsSync(partialPath)) {
    fs.writeFileSync(partialPath, DEFAULT_PARTIAL);
    console.error(`Created partial file: ${partialPath}`);
  } else {
    console.error(`Partial file already exists: ${partialPath}`);
  }

  // Create templates directory and file
  if (!fs.existsSync(templatesDir)) {
    fs.mkdirSync(templatesDir, { recursive: true });
  }
  const templatePath = path.join(templatesDir, 'gemini.md.tmpl');
  if (!fs.existsSync(templatePath)) {
    fs.writeFileSync(templatePath, DEFAULT_TEMPLATE);
    console.error(`Created template file: ${templatePath}`);
  } else {
    console.error(`Template file already exists: ${templatePath}`);
  }

  console.error('\nProject initialized successfully!');
}
